apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnews-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: cnews-sv-mariadb
        - name: WORDPRESS_DB_NAME
          value: wp-camara
        - name: WORDPRESS_DB_PASSWORD
          value: wp-pass
        - name: WORDPRESS_DB_USER
          value: wp-user
        - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
          value: 
            define('VIDEO_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/video');
            define('VIDEO_UPLOAD_URL', 'http://localhost:8282/wp-content/uploads/midias/video');
            define('IMAGE_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/image');
            define('IMAGE_UPLOAD_URL', 'http://localhost:8282/wp-content/uploads/midias/image');
            define('AUDIO_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/audio');
            define('AUDIO_UPLOAD_URL', 'http://localhost:8282/wp-content/uploads/midias/audio');
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cnews-service-wp
spec:
  selector:
      app: sv-wp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnews-mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.11
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root@1234
        - name: MYSQL_DATABASE
          value: wp-camara
        - name: MYSQL_USER
          value: wp-user
        - name: MYSQL_PASSWORD
          value: wp-pass
      volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
    volumes:
    - name: mariadb-persistent-storage
      persistentVolumeClaim:
        claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cnews-sv-mariadb
spec:
  selector:
      app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
